'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Typing.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Black_background_set_wood_on_chanconsultants_jpg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Black_background_set_wood_on_chanconsultants_jpg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Capture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Capture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FastTyping() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FastTyping", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property machinetop_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("machinetop_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Luckily, the wisest little pig had been watching the scene from the window
        '''of his own brick house, and he rapidly opened the door to his fleeing 
        '''brothers. And not a moment too soon, for the wolf was already hammering 
        '''furiously on the door. This time, the wolf had grave doubts. This house had a
        '''much more solid air than the others. He blew once, he blew again and then for
        '''a third time. But all was in vain. For the house did not budge an lnch. The
        '''three little pigs watched him and their fear began to f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story1() As String
            Get
                Return ResourceManager.GetString("story1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One Christmas was so much like another, in those years around the sea-town corner now and out of all sound except the distant speaking of the voices I sometimes hear a moment before sleep, that I can never remember whether it snowed for six days and six nights when I was twelve or whether it snowed for twelve days and twelve nights when I was six. All the Christmases roll down toward the two-tongued sea, like a cold and headlong moon bundling down the sky that was our street; and they stop at the rim of the [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story10() As String
            Get
                Return ResourceManager.GetString("story10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About half of all practitioners today have degrees in computer science, information systems, or information technology. A small, but growing, number of practitioners have software engineering degrees. In 1987, Imperial College London introduced the first three-year software engineering Bachelor&apos;s degree in the UK and the world; in the following year, the University of Sheffield established a similar program. In 1996, the Rochester Institute of Technology established the first software engineering Bachelor&apos;s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story2() As String
            Get
                Return ResourceManager.GetString("story2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maupassant made two divisions of his spare hours, one for boating, and
        '''the other for literature. Every evening in spring, every free day,
        '''he ran down to the river whose mysterious current veiled in fog or
        '''sparkling in the sun called to him and bewitched him. In the islands in
        '''the Seine between Chatou and Port-Marly, on the banks of Sartrouville
        '''and Triel he was long noted among the population of boatmen, who
        '''have now vanished, for his unwearying biceps, his cynical gaiety of
        '''good-fellowship, his unfa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story3() As String
            Get
                Return ResourceManager.GetString("story3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The afternoon was wretched. They could not understand the caprice of
        '''this German, and the strangest ideas came into their heads. They all
        '''congregated in the kitchen, and talked the subject to death, imagining
        '''all kinds of unlikely things. Perhaps they were to be kept as hostages
        '''--but for what reason? or to be extradited as prisoners of war? or
        '''possibly they were to be held for ransom? They were panic-stricken at
        '''this last supposition. The richest among them were the most alarmed,
        '''seeing themselves f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story4() As String
            Get
                Return ResourceManager.GetString("story4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For several days in succession fragments of a defeated army had passed
        '''through the town. They were mere disorganized bands, not disciplined
        '''forces. The men wore long, dirty beards and tattered uniforms; they
        '''advanced in listless fashion, without a flag, without a leader. All
        '''seemed exhausted, worn out, incapable of thought or resolve, marching
        '''onward merely by force of habit, and dropping to the ground with fatigue
        '''the moment they halted. One saw, in particular, many enlisted men,
        '''peaceful citizens,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story5() As String
            Get
                Return ResourceManager.GetString("story5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to At the end of a short time, once the first terror had subsided, calm
        '''was again restored. In many houses the Prussian officer ate at the same
        '''table with the family. He was often well-bred, and, out of politeness,
        '''expressed sympathy with France and repugnance at being compelled to take
        '''part in the war. This sentiment was received with gratitude; besides,
        '''his protection might be needful some day or other. By the exercise of
        '''tact the number of men quartered in one&apos;s house might be reduced; and
        '''why should [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story6() As String
            Get
                Return ResourceManager.GetString("story6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As they had decided on starting at eight o&apos;clock the next morning, every
        '''one was in the kitchen at that hour; but the coach, its roof covered
        '''with snow, stood by itself in the middle of the yard, without either
        '''horses or driver. They sought the latter in the stables, coach-houses
        '''and barns --but in vain. So the men of the party resolved to scour
        '''the country for him, and sallied forth. They found them selves in the
        '''square, with the church at the farther side, and to right and left
        '''low-roofed houses wh [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story7() As String
            Get
                Return ResourceManager.GetString("story7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to But at dinner the coalition weakened. Loiseau made three unfortunate
        '''remarks. Each was cudgeling his brains for further examples of
        '''self-sacrifice, and could find none, when the countess, possibly without
        '''ulterior motive, and moved simply by a vague desire to do homage to
        '''religion, began to question the elder of the two nuns on the most
        '''striking facts in the lives of the saints. Now, it fell out that many
        '''of these had committed acts which would be crimes in our eyes, but the
        '''Church readily pardons su [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story8() As String
            Get
                Return ResourceManager.GetString("story8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Then he sat down and began to reflect. In the morning he must find seconds. Whom should he choose? He searched his mind for the most important and celebrated names of his acquaintance. At last he decided on the Marquis de la Tour-Noire and Colonel Bourdin, an aristocrat and a soldier; they would do excellently. Their names would look well in the papers. He realised that he was thirsty, and drank three glasses of water one after the other; then he began to walk up and down again. He felt full of energy. If h [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property story9() As String
            Get
                Return ResourceManager.GetString("story9", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
